// import './Stories/ButtonOutline.story';
// import './Stories/LoginInputField.story';
// import './Stories/InputField.story';
// import './Stories/RadioButton.story';
// import './Stories/ButtonPrimary.story';
// import './Stories/CheckBox.story';
// import './Stories/ButtonPrimary.story';
// import './Stories/StepsIndicators.story';
// import './Stories/CellWithSwitch.story';
// import './Stories/ScheduleBoundariesView.story';
// import './Stories/UniversalCell.story';
// import './Stories/CollectionGroup.story';
// import './Stories/DefaultAvatar.story';
// import './Stories/ProfileHeader.story';
// import './Stories/ProfileLabel.story';
// import './Stories/ListHeader.story';
// import './Stories/Slot.story';
// import './Stories/DialogBox.story';
// import './Stories/SearchInput.story';
import './Stories/SlotLayout.story';
import './Stories/SlotBookingBy3rdPart.story';
import './Stories/FreeSlot.story';
import './Stories/DriveSlot.story';
import './Stories/SelectedSlot.story';
