export default FORMS_IDS = {
  BASIC_INFO: 'BASIC_INFO',
  USER_NOTIFICATIONS: 'USER_NOTIFICATIONS',
  SCHEDULE_BOUNDARIES: 'SCHEDULE_BOUNDARIES',
  SCHEDULE_SETTINGS: 'SCHEDULE_SETTINGS',
  CONFIRM_REGISTRATION: 'CONFIRM_REGISTRATION'
};
